apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-scan-manual
spec:
  template:
    spec:
      containers:
      - name: trivy
        image: aquasec/trivy:latest
        args: ["image", "--severity", "HIGH,CRITICAL", "--exit-code", "1", "your-repo/your-image:latest"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: OnFailure
